---
# tasks file for signal
- name: Install Signal apt repo GPG key.
  become: yes
  apt_key:
    id: "DBA36B5181D0C816F630E889D980A17457F6FB06"
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

- name: Add Signal apt repo.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    state: present

- name: Installs Signal desktop.
  become: yes
  apt:
    name: signal-desktop
    state: present
