---
# tasks file for firefox-extensions
- name: Create policy directory
  become: true
  file: path="/etc/firefox/policies" state=directory

- name: Place policy
  become: true
  copy:
    src: policies.json
    dest: "/etc/firefox/policies/policies.json"
