---
# tasks file for i3
- name: Install i3 Packages
  become: true
  apt:
    pkg:
      - i3
      - i3status
      - rofi

- name: Create i3 directory
  ansible.builtin.file:
    path: ~/.config/i3/
    state: directory

- name: custom i3 config
  blockinfile:
    create: yes
    block: |
      # Please see https://i3wm.org/docs/userguide.html for a complete reference!
      set $mod Mod4
      font pango:monospace 12
      exec --no-startup-id xss-lock --transfer-sleep-lock -- slock
      exec --no-startup-id nm-applet
      set $refresh_i3status killall -SIGUSR1 i3status
      bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
      bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
      bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
      bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
      floating_modifier $mod
      bindsym $mod+Return exec urxvtc -e bash -c "exec tmux new-session"
      bindsym $mod+c kill
      bindsym $mod+p exec "rofi -modi drun,window,run,combi,ssh -show combi -matching fuzzy -sidebar-mode -terminal urxvtcd -no-disable-history -sort -sorting-method fzf"
      bindsym $mod+h focus left
      bindsym $mod+j focus down
      bindsym $mod+k focus up
      bindsym $mod+l focus right
      bindsym $mod+Shift+h move left
      bindsym $mod+Shift+j move down
      bindsym $mod+Shift+k move up
      bindsym $mod+Shift+l move right
      bindsym $mod+Shift+v split h
      bindsym $mod+v split v
      bindsym $mod+Shift+f fullscreen toggle
      bindsym $mod+s layout stacking
      bindsym $mod+w layout tabbed
      bindsym $mod+e layout toggle split
      bindsym $mod+Shift+space floating toggle
      bindsym $mod+space focus mode_toggle
      bindsym $mod+a focus parent
      bindsym $mod+Shift+d focus child
      set $ws1 "1"
      set $ws2 "2"
      set $ws3 "3"
      set $ws4 "4"
      set $ws5 "5"
      set $ws6 "6"
      set $ws7 "7"
      set $ws8 "8"
      set $ws9 "9"
      set $ws10 "10"
      bindsym $mod+1 workspace number $ws1
      bindsym $mod+2 workspace number $ws2
      bindsym $mod+3 workspace number $ws3
      bindsym $mod+4 workspace number $ws4
      bindsym $mod+5 workspace number $ws5
      bindsym $mod+6 workspace number $ws6
      bindsym $mod+7 workspace number $ws7
      bindsym $mod+8 workspace number $ws8
      bindsym $mod+9 workspace number $ws9
      bindsym $mod+0 workspace number $ws10
      bindsym $mod+Shift+1 move container to workspace number $ws1
      bindsym $mod+Shift+2 move container to workspace number $ws2
      bindsym $mod+Shift+3 move container to workspace number $ws3
      bindsym $mod+Shift+4 move container to workspace number $ws4
      bindsym $mod+Shift+5 move container to workspace number $ws5
      bindsym $mod+Shift+6 move container to workspace number $ws6
      bindsym $mod+Shift+7 move container to workspace number $ws7
      bindsym $mod+Shift+8 move container to workspace number $ws8
      bindsym $mod+Shift+9 move container to workspace number $ws9
      bindsym $mod+Shift+0 move container to workspace number $ws10
      bindsym $mod+Shift+c reload
      bindsym $mod+Shift+r restart
      bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
      mode "resize" {
              bindsym h resize shrink width 10 px or 10 ppt
              bindsym j resize grow height 10 px or 10 ppt
              bindsym k resize shrink height 10 px or 10 ppt
              bindsym l resize grow width 10 px or 10 ppt
              bindsym Return mode "default"
              bindsym Escape mode "default"
              bindsym $mod+r mode "default"
      }
      bindsym $mod+r mode "resize"
      bar {
              status_command i3status
              position top
      }
      focus_follows_mouse no
      client.focused          #990000 #990000 #000000 #009900   #990000
      bindsym $mod+Shift+p exec playerctl play-pause
      bindsym $mod+f exec playerctl next
      bindsym $mod+b exec playerctl previous
    path: ~/.config/i3/config
    marker: "# {mark} custom-config"

- name: Create i3status directory
  ansible.builtin.file:
    path: ~/.config/i3status/
    state: directory

- name: custom i3status config
  blockinfile:
    create: yes
    block: |
      general {
              colors = true
      }
      order += "load"
      order += "cpu_temperature 0"
      order += "volume master"
      order += "cpu_usage"
      order += "memory"
      order += "disk /home"
      order += "tztime local"
      cpu_usage {
              format = " Cpu %usage "
              max_threshold = 75
      }
      volume master {
              format = " Vol %volume "
              format_muted = " Vol muted "
              device = "default"
              mixer = "Master"
              mixer_idx = 0
      }
      tztime local {
              format = " %Y-%m-%d %H:%M "
      }
      load {
              format = " %1min %5min %15min "
      }
      memory {
              format = " Mem %percentage_used "
              threshold_degraded = "10%"
              format_degraded = "MEMORY: %free"
      }
      disk "/home" {
              format = " HDD %percentage_used "
      }
      cpu_temperature 0 {
              format = " T: %degrees °C "
              path = "/sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input"
      }
    path: ~/.config/i3status/config
    marker: "# {mark} custom-config"
