---
# tasks file for oh-my-zsh
- name: Clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: ~/.oh-my-zsh

- name: custom config
  blockinfile:
    block: |
      export ZSH=$HOME/.oh-my-zsh
      source $ZSH/oh-my-zsh.sh
    path: ~/.zshrc
    marker: "# {mark} source-oh-my-zsh"

- include: plugins.yml
