---
# tasks file for oh-my-zsh
- name: Clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: ~/.oh-my-zsh

- include: plugins.yml

- name: custom config
  blockinfile:
    insertafter: "# END plugins"
    block: |
      export ZSH=$HOME/.oh-my-zsh
      source $ZSH/oh-my-zsh.sh
      ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
    path: ~/.zshrc
    marker: "# {mark} source-oh-my-zsh"
