---
# tasks file for emacs
- name: Install Emacs Packages
  become: true
  apt:
    pkg:
      - emacs

- name: User systemd directory
  file: path="~/.config/systemd/user/" state=directory

- name: Emacs Daemon
  systemd:
    enabled: true
    state: started
    scope: user
    name: emacs.service

- name: custom config
  blockinfile:
    block: |
      export EDITOR="emacsclient -t -a emacs"
      export VISUAL="emacsclient -c -a emacs"
    path: ~/.zshrc
    marker: "# {mark} emacs"
