---
# tasks file for thefuck
- name: Install thefuck
  pip:
    name: thefuck
    executable: pip3

- name: Add to zsh
  blockinfile:
    block: |
      eval $(thefuck --alias)
    path: ~/.zshrc
    marker: "# {mark} thefuck"
