---
# tasks file for use-zsh
- name: set up zsh for user
  become: no
  vars:
    user_id: "{{ ansible_user_id }}"
  tasks:
    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ user_id }}"
        shell: /bin/zsh
