---
# tasks file for urxvt
- name: Install urxvt Packages
  become: true
  apt:
    pkg:
      - rxvt-unicode

- name: Create systemd directory
  ansible.builtin.file:
    path: ~/.config/systemd/user/
    state: directory

- name: install urxvtd service
  copy:
    src: urxvtd.service
    dest: ~/.config/systemd/user/urxvtd.service

- name: enable urxvtd service
  service:
    name: urxvtd
    enabled: yes
    user: yes

- name: start urxvtd
  service:
    name: urxvtd
    state: started
    user: yes
